imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%.log"
            level:    debug
            channels: ['!event']
        firephp:
            type:     firephp
            level:    info
        console:
            type:     console
            channels: ['!event', '!doctrine']

oro_assetic:
    css_debug:      ~
    css_debug_all:  false

swiftmailer:
    disable_delivery: true

services:
    # This service is active only in dev and test environments.
    # To activate it in prod environement, you must redeclare this service in your standard edition configuration
    security.event_listener.add_csp:
        class: Pim\Bundle\UIBundle\EventListener\AddContentSecurityPolicyListener
        arguments:
            - '@security.script_nonce_generator'
        tags:
            - { name: kernel.event_subscriber }
